import cv2 as cv
import os

# Membuat folder penyimpanan jika belum ada
folder_output = 'tugas_kelompok_10'
os.makedirs(folder_output, exist_ok=True)

# Membaca citra berwarna
img_rgb = cv.imread('gambar_soal.jpeg', cv.IMREAD_COLOR)

# Membaca citra grayscale
img_gray = cv.imread('gambar_soal.jpeg', cv.IMREAD_GRAYSCALE)

# Membaca citra biner tiap nilai threshold (10 sampai 240)
_, img_binary_10 = cv.threshold(img_gray, 10, 255, cv.THRESH_BINARY)
_, img_binary_20 = cv.threshold(img_gray, 20, 255, cv.THRESH_BINARY)
_, img_binary_30 = cv.threshold(img_gray, 30, 255, cv.THRESH_BINARY)
_, img_binary_40 = cv.threshold(img_gray, 40, 255, cv.THRESH_BINARY)
_, img_binary_50 = cv.threshold(img_gray, 50, 255, cv.THRESH_BINARY)
_, img_binary_60 = cv.threshold(img_gray, 60, 255, cv.THRESH_BINARY)
_, img_binary_70 = cv.threshold(img_gray, 70, 255, cv.THRESH_BINARY)
_, img_binary_80 = cv.threshold(img_gray, 80, 255, cv.THRESH_BINARY)
_, img_binary_90 = cv.threshold(img_gray, 90, 255, cv.THRESH_BINARY)
_, img_binary_100 = cv.threshold(img_gray, 100, 255, cv.THRESH_BINARY)
_, img_binary_110 = cv.threshold(img_gray, 110, 255, cv.THRESH_BINARY)
_, img_binary_120 = cv.threshold(img_gray, 120, 255, cv.THRESH_BINARY)
_, img_binary_130 = cv.threshold(img_gray, 130, 255, cv.THRESH_BINARY)
_, img_binary_140 = cv.threshold(img_gray, 140, 255, cv.THRESH_BINARY)
_, img_binary_150 = cv.threshold(img_gray, 150, 255, cv.THRESH_BINARY)
_, img_binary_160 = cv.threshold(img_gray, 160, 255, cv.THRESH_BINARY)
_, img_binary_170 = cv.threshold(img_gray, 170, 255, cv.THRESH_BINARY)
_, img_binary_180 = cv.threshold(img_gray, 180, 255, cv.THRESH_BINARY)
_, img_binary_190 = cv.threshold(img_gray, 190, 255, cv.THRESH_BINARY)
_, img_binary_200 = cv.threshold(img_gray, 200, 255, cv.THRESH_BINARY)
_, img_binary_210 = cv.threshold(img_gray, 210, 255, cv.THRESH_BINARY)
_, img_binary_220 = cv.threshold(img_gray, 220, 255, cv.THRESH_BINARY)
_, img_binary_230 = cv.threshold(img_gray, 230, 255, cv.THRESH_BINARY)
_, img_binary_240 = cv.threshold(img_gray, 240, 255, cv.THRESH_BINARY)

# Menyimpan hasil grayscale ke dalam folder
cv.imwrite(f'{folder_output}/Kelas_grayscale.jpg', img_gray)

# Menyimpan hasil citra biner tiap rentang ke dalam folder
cv.imwrite(f'{folder_output}/Kelas_binary_10.jpg', img_binary_10)
cv.imwrite(f'{folder_output}/Kelas_binary_20.jpg', img_binary_20)
cv.imwrite(f'{folder_output}/Kelas_binary_30.jpg', img_binary_30)
cv.imwrite(f'{folder_output}/Kelas_binary_40.jpg', img_binary_40)
cv.imwrite(f'{folder_output}/Kelas_binary_50.jpg', img_binary_50)
cv.imwrite(f'{folder_output}/Kelas_binary_60.jpg', img_binary_60)
cv.imwrite(f'{folder_output}/Kelas_binary_70.jpg', img_binary_70)
cv.imwrite(f'{folder_output}/Kelas_binary_80.jpg', img_binary_80)
cv.imwrite(f'{folder_output}/Kelas_binary_90.jpg', img_binary_90)
cv.imwrite(f'{folder_output}/Kelas_binary_100.jpg', img_binary_100)
cv.imwrite(f'{folder_output}/Kelas_binary_110.jpg', img_binary_110)
cv.imwrite(f'{folder_output}/Kelas_binary_120.jpg', img_binary_120)
cv.imwrite(f'{folder_output}/Kelas_binary_130.jpg', img_binary_130)
cv.imwrite(f'{folder_output}/Kelas_binary_140.jpg', img_binary_140)
cv.imwrite(f'{folder_output}/Kelas_binary_150.jpg', img_binary_150)
cv.imwrite(f'{folder_output}/Kelas_binary_160.jpg', img_binary_160)
cv.imwrite(f'{folder_output}/Kelas_binary_170.jpg', img_binary_170)
cv.imwrite(f'{folder_output}/Kelas_binary_180.jpg', img_binary_180)
cv.imwrite(f'{folder_output}/Kelas_binary_190.jpg', img_binary_190)
cv.imwrite(f'{folder_output}/Kelas_binary_200.jpg', img_binary_200)
cv.imwrite(f'{folder_output}/Kelas_binary_210.jpg', img_binary_210)
cv.imwrite(f'{folder_output}/Kelas_binary_220.jpg', img_binary_220)
cv.imwrite(f'{folder_output}/Kelas_binary_230.jpg', img_binary_230)
cv.imwrite(f'{folder_output}/Kelas_binary_240.jpg', img_binary_240)

# Menampilkan citra
cv.imshow('Citra Berwarna', img_rgb)
cv.imshow('Citra Grayscale', img_gray)
cv.imshow('Citra Biner 10', img_binary_10)
cv.imshow('Citra Biner 20', img_binary_20)
cv.imshow('Citra Biner 30', img_binary_30)
cv.imshow('Citra Biner 40', img_binary_40)
cv.imshow('Citra Biner 50', img_binary_50)
cv.imshow('Citra Biner 60', img_binary_60)
cv.imshow('Citra Biner 70', img_binary_70)
cv.imshow('Citra Biner 80', img_binary_80)
cv.imshow('Citra Biner 90', img_binary_90)
cv.imshow('Citra Biner 100', img_binary_100)
cv.imshow('Citra Biner 110', img_binary_110)
cv.imshow('Citra Biner 120', img_binary_120)
cv.imshow('Citra Biner 130', img_binary_130)
cv.imshow('Citra Biner 140', img_binary_140)
cv.imshow('Citra Biner 150', img_binary_150)
cv.imshow('Citra Biner 160', img_binary_160)
cv.imshow('Citra Biner 170', img_binary_170)
cv.imshow('Citra Biner 180', img_binary_180)
cv.imshow('Citra Biner 190', img_binary_190)
cv.imshow('Citra Biner 200', img_binary_200)
cv.imshow('Citra Biner 210', img_binary_210)
cv.imshow('Citra Biner 220', img_binary_220)
cv.imshow('Citra Biner 230', img_binary_230)
cv.imshow('Citra Biner 240', img_binary_240)

cv.waitKey(0)
cv.destroyAllWindows()
